# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: attachment.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'attachment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import options_pb2 as options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61ttachment.proto\x12\x13warp.multi_agent.v1\x1a\roptions.proto\"\xfd\x01\n\nAttachment\x12\x14\n\nplain_text\x18\x01 \x01(\tH\x00\x12K\n\x16\x65xecuted_shell_command\x18\x02 \x01(\x0b\x32).warp.multi_agent.v1.ExecutedShellCommandH\x00\x12I\n\x15running_shell_command\x18\x03 \x01(\x0b\x32(.warp.multi_agent.v1.RunningShellCommandH\x00\x12\x38\n\x0c\x64rive_object\x18\x04 \x01(\x0b\x32 .warp.multi_agent.v1.DriveObjectH\x00\x42\x07\n\x05value\"J\n\x14\x45xecutedShellCommand\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x0e\n\x06output\x18\x02 \x01(\t\x12\x11\n\texit_code\x18\x03 \x01(\x05\"n\n\x13RunningShellCommand\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x46\n\x08snapshot\x18\x02 \x01(\x0b\x32\x34.warp.multi_agent.v1.LongRunningShellCommandSnapshot\"1\n\x1fLongRunningShellCommandSnapshot\x12\x0e\n\x06output\x18\x01 \x01(\t\"\xdd\x01\n\x0b\x44riveObject\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x31\n\x08workflow\x18\x02 \x01(\x0b\x32\x1d.warp.multi_agent.v1.WorkflowH\x00\x12\x31\n\x08notebook\x18\x03 \x01(\x0b\x32\x1d.warp.multi_agent.v1.NotebookH\x00\x12I\n\x15generic_string_object\x18\x04 \x01(\x0b\x32(.warp.multi_agent.v1.GenericStringObjectH\x00\x42\x10\n\x0eobject_payload\">\n\x08Workflow\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x03 \x01(\t\"*\n\x08Notebook\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\";\n\x13GenericStringObject\x12\x0f\n\x07payload\x18\x01 \x01(\t\x12\x13\n\x0bobject_type\x18\x02 \x01(\tB0Z.github.com/warp/warp-proto-apis/multi_agent/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'attachment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z.github.com/warp/warp-proto-apis/multi_agent/v1'
  _globals['_ATTACHMENT']._serialized_start=57
  _globals['_ATTACHMENT']._serialized_end=310
  _globals['_EXECUTEDSHELLCOMMAND']._serialized_start=312
  _globals['_EXECUTEDSHELLCOMMAND']._serialized_end=386
  _globals['_RUNNINGSHELLCOMMAND']._serialized_start=388
  _globals['_RUNNINGSHELLCOMMAND']._serialized_end=498
  _globals['_LONGRUNNINGSHELLCOMMANDSNAPSHOT']._serialized_start=500
  _globals['_LONGRUNNINGSHELLCOMMANDSNAPSHOT']._serialized_end=549
  _globals['_DRIVEOBJECT']._serialized_start=552
  _globals['_DRIVEOBJECT']._serialized_end=773
  _globals['_WORKFLOW']._serialized_start=775
  _globals['_WORKFLOW']._serialized_end=837
  _globals['_NOTEBOOK']._serialized_start=839
  _globals['_NOTEBOOK']._serialized_end=881
  _globals['_GENERICSTRINGOBJECT']._serialized_start=883
  _globals['_GENERICSTRINGOBJECT']._serialized_end=942
# @@protoc_insertion_point(module_scope)
