# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file_content.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'file_content.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import options_pb2 as options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x66ile_content.proto\x12\x13warp.multi_agent.v1\x1a\roptions.proto\"2\n\x14\x46ileContentLineRange\x12\r\n\x05start\x18\x01 \x01(\r\x12\x0b\n\x03\x65nd\x18\x02 \x01(\r\"p\n\x0b\x46ileContent\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12=\n\nline_range\x18\x03 \x01(\x0b\x32).warp.multi_agent.v1.FileContentLineRangeB0Z.github.com/warp/warp-proto-apis/multi_agent/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_content_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z.github.com/warp/warp-proto-apis/multi_agent/v1'
  _globals['_FILECONTENTLINERANGE']._serialized_start=58
  _globals['_FILECONTENTLINERANGE']._serialized_end=108
  _globals['_FILECONTENT']._serialized_start=110
  _globals['_FILECONTENT']._serialized_end=222
# @@protoc_insertion_point(module_scope)
