# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{

  celld = {
    pname = "celld";
    version = "v0.1.0";
    src = fetchFromGitHub {
      owner = "denoland";
      repo = "celld";
      rev = "v0.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-Iew3/ugHftS1Ui6tiVRPj3FguYmGx9vwMfS6pY00CWQ=";
    };
  };

  cliproxyapi = {
    pname = "cliproxyapi";
    version = "v7.2.127";
    src = fetchFromGitHub {
      owner = "router-for-me";
      repo = "CLIProxyAPI";
      rev = "v7.2.127";
      fetchSubmodules = false;
      sha256 = "sha256-gVy/bErDmZnKrbp4CwMBjFqIhdLGmqVN34bTF2gqWmQ=";
    };
  };
  cloakbrowser = {
    pname = "cloakbrowser";
    version = "146.0.7680.177.5";
    src = fetchurl {
      url = "https://cloakbrowser.dev/chromium-v146.0.7680.177.5/cloakbrowser-linux-x64.tar.gz";
      sha256 = "sha256-ShK83pX6G7G+7ytBq15cJ8Nr544749DayMZNcFIWZw4=";
    };
  };

  coe = {
    pname = "coe";
    version = "c326261675a2455e6dd8c22576681e91644600ef";
    src = fetchgit {
      url = "https://github.com/p3psi-boo/coe.git";
      rev = "c326261675a2455e6dd8c22576681e91644600ef";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-0VL8NsKi1zl8fWJHn9khUwb0Jx0NIEvAdqe7slSfPyw=";
    };
    date = "2026-04-23";
  };
  commandcode2api = {
    pname = "commandcode2api";
    version = "1010b2292ebd626d16662f878350e173286110c2";
    src = fetchgit {
      url = "https://github.com/p3psi-boo/commandcode2api.git";
      rev = "1010b2292ebd626d16662f878350e173286110c2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-rMry5ozjcwK044CivmqEwTUajKId2PYIs3NOGjh0gjk=";
    };
    date = "2026-08-15";
  };
  cookiecloud-rs = {
    pname = "cookiecloud-rs";
    version = "f8a023f42951c8ba97261d3b16e3a4ff53c91f4a";
    src = fetchgit {
      url = "https://github.com/p3psi-boo/CookieCloud.git";
      rev = "f8a023f42951c8ba97261d3b16e3a4ff53c91f4a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ak78lDOAaDWCk9dNpQ9nNObwXrhj71umhzu01hagt2I=";
    };
    date = "2026-04-14";
  };

  ecloud-cloudpc-keepalive = {
    pname = "ecloud-cloudpc-keepalive";
    version = "d8625ec87671814f14b4275f7dbe7eb05039fa5b";
    src = fetchFromGitHub {
      owner = "p3psi-boo";
      repo = "ecloud-cloudpc-keepalive";
      rev = "d8625ec87671814f14b4275f7dbe7eb05039fa5b";
      fetchSubmodules = false;
      sha256 = "sha256-4wIZf7JPHgpdcxSfrIlA51nCPyg78NoZreqo8REh124=";
    };
    date = "2026-07-14";
  };

  einat = {
    pname = "einat";
    version = "30e6af3740e279efb254568c0ec1ad54c0cccd35";
    src = fetchgit {
      url = "https://github.com/EHfive/einat-ebpf.git";
      rev = "30e6af3740e279efb254568c0ec1ad54c0cccd35";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-QPvyJGd35V5D8Q9mZUPNt8kfpG75qNHxr30oQkfDcV0=";
    };
    date = "2026-06-27";
  };

  focaltech-fingerprint = {
    pname = "focaltech-fingerprint";
    version = "d4fbbf901aff44b92d4fa212d9b99e43cda00563";
    src = fetchgit {
      url = "https://github.com/vobademi/FTEXX00-Ubuntu.git";
      rev = "d4fbbf901aff44b92d4fa212d9b99e43cda00563";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-0mnXEQjSWUrz8uSwaeWH6uLLZtGnSUx5OPBxjPNxFTs=";
    };
    date = "2025-10-21";
  };
  fusion = {
    pname = "fusion";
    version = "ecc44eeff94dd4836eed6490a497989194effa2b";
    src = fetchgit {
      url = "https://github.com/p3psi-boo/fusion.git";
      rev = "ecc44eeff94dd4836eed6490a497989194effa2b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-O9NMromcyvcF97Kb084vrHPjqRgyRqq14Ay8pdsj9rQ=";
    };
    date = "2026-04-12";
  };

  grok2api = {
    pname = "grok2api";
    version = "ef7fb4f224062be15ab8745389a5c13ab4dc846b";
    src = fetchgit {
      url = "https://github.com/jiujiu532/grok2api.git";
      rev = "ef7fb4f224062be15ab8745389a5c13ab4dc846b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-FLYqGRSY47IGrA0j08U5PCfyWMEe8clFlGM5TBP4Ulw=";
    };
    date = "2026-07-09";
  };
  harlequin-mysql = {
    pname = "harlequin-mysql";
    version = "v1.3.1";
    src = fetchFromGitHub {
      owner = "tconbeer";
      repo = "harlequin-mysql";
      rev = "v1.3.1";
      fetchSubmodules = false;
      sha256 = "sha256-haY8LTzcXm7+peKl9rzv1AE8jktBUsK2S6R0vzXHmTQ=";
    };
  };

  ironet = {
    pname = "ironet";
    version = "d6988356fe688d1ea234ec92c00ce537318f6f20";
    src = fetchgit {
      url = "https://github.com/p3psi-boo/ironet.git";
      rev = "d6988356fe688d1ea234ec92c00ce537318f6f20";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-l70gtKEGayGDGSSm1d7Rk4gWupT8lSr9psI5ID8jynA=";
    };
    date = "2026-08-14";
  };

  komari = {
    pname = "komari";
    version = "14bf8bde7cf1313e674e4bf28198f84e9b934794";
    src = fetchgit {
      url = "https://github.com/komari-monitor/komari.git";
      rev = "14bf8bde7cf1313e674e4bf28198f84e9b934794";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ep83GqGCUiqthzzx9mV0Bvl76divEvps1R/meUYUKIM=";
    };
    date = "2026-08-07";
  };
  komari-agent-zig = {
    pname = "komari-agent-zig";
    version = "41555ce88a322dbaab229e81120a7bb130d230ea";
    src = fetchgit {
      url = "https://github.com/luodaoyi/komari-zig-agent.git";
      rev = "41555ce88a322dbaab229e81120a7bb130d230ea";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-VJmH4lR6XrlD00EJvJEts8ShEBMQ6LWrqeHeJkymbco=";
    };
    date = "2026-08-11";
  };
  komari-web = {
    pname = "komari-web";
    version = "f625b348b339fcb9f699bf7b5028d6678cfc0ab9";
    src = fetchgit {
      url = "https://github.com/komari-monitor/komari-web.git";
      rev = "f625b348b339fcb9f699bf7b5028d6678cfc0ab9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-sXBl8Kwulv2qwEco66WrHVIB6OGHEAFSGP40DtEEQx0=";
    };
    date = "2026-08-06";
  };
  lazyssh = {
    pname = "lazyssh";
    version = "48995806bf1aa1c9c41bb8dff6b5ddd698539311";
    src = fetchgit {
      url = "https://github.com/p3psi-boo/lazyssh.git";
      rev = "48995806bf1aa1c9c41bb8dff6b5ddd698539311";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-/jywzjLZ51nSbiDbhw3H1eES3p0sZ9MSayGjJFQ+RKM=";
    };
    date = "2025-11-28";
  };

  lotspeed = {
    pname = "lotspeed";
    version = "df78e23472f2d291ee41cca2d308f67d5828fb22";
    src = fetchgit {
      url = "https://github.com/uk0/lotspeed.git";
      rev = "df78e23472f2d291ee41cca2d308f67d5828fb22";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-br29pDUjrNCS2BL+u3ZTixyYR3iKj6fn8WvQQE+T63Y=";
    };
    date = "2026-06-18";
  };

  micyou = {
    pname = "micyou";
    version = "v1.3.5";
    src = fetchFromGitHub {
      owner = "LanRhyme";
      repo = "MicYou";
      rev = "v1.3.5";
      fetchSubmodules = false;
      sha256 = "sha256-qefp7gG7DfE/GN81UB981KvS4Q2oIxNLM2/76NLacXs=";
    };
  };

  n9router = {
    pname = "n9router";
    version = "a7d5780a9fe16ee31a39010af9b892033c1d58fc";
    src = fetchgit {
      url = "https://github.com/nightwalker89/n9router.git";
      rev = "a7d5780a9fe16ee31a39010af9b892033c1d58fc";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-N6H0+C+SK/K4gJCPJAqe5kTpBkHuYLRu6+OE2nBOAXE=";
    };
    date = "2026-08-08";
  };

  octopus-api = {
    pname = "octopus-api";
    version = "7b7a4801fa501f9244a1d9dfb47da56d1600b970";
    src = fetchgit {
      url = "https://github.com/p3psi-boo/octopus.git";
      rev = "7b7a4801fa501f9244a1d9dfb47da56d1600b970";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-pwKEYRAPnPwElyFhh4tI+vVV/BMLLCFnFIpgotMd0Wc=";
    };
    date = "2026-08-06";
  };

  picoclaw = {
    pname = "picoclaw";
    version = "v0.3.1";
    src = fetchFromGitHub {
      owner = "sipeed";
      repo = "picoclaw";
      rev = "v0.3.1";
      fetchSubmodules = false;
      sha256 = "sha256-QYfHXIHJjeZJdkhGNNhdO91Q8EFgSP+ubqGJ8VgTEtc=";
    };
  };
  piko = {
    pname = "piko";
    version = "v0.1.5";
    src = fetchFromGitHub {
      owner = "UruhaLushia";
      repo = "piko";
      rev = "v0.1.5";
      fetchSubmodules = false;
      sha256 = "sha256-36JrU8a+XUUUiQT39x9495/xk1zjP1q+OlMcR7ZPq9o=";
    };
  };

  powermem = {
    pname = "powermem";
    version = "1.1.7";
    src = fetchurl {
      url = "https://github.com/oceanbase/powermem/releases/download/v1.1.7/powermem-1.1.7-linux-amd64-binaries.tar.gz";
      sha256 = "sha256-CmicB7f9t4RJ7QCQVWduaFn6TqcE4CalI3SDOvnl6/g=";
    };
  };
  proxy-ns = {
    pname = "proxy-ns";
    version = "5d08d18f9171d7e65fabad06ee81021d9bca0a21";
    src = fetchgit {
      url = "https://github.com/OkamiW/proxy-ns.git";
      rev = "5d08d18f9171d7e65fabad06ee81021d9bca0a21";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-4w5aiVpbmlGkCyg5YQnjXYkdgrbZADiWw+l4kd6ecek=";
    };
    date = "2026-04-09";
  };

  searxng-baidu-qianfan-bridge = {
    pname = "searxng-baidu-qianfan-bridge";
    version = "a9826ab251fa3d52a59a3900f702ab53cd602793";
    src = fetchgit {
      url = "https://github.com/p3psi-boo/searxng-baidu-qianfan-bridge.git";
      rev = "a9826ab251fa3d52a59a3900f702ab53cd602793";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-oaPrdnj4OBjTyxeMKDVBpxzbGMoSQjLc1lvbRdLCeCs=";
    };
    date = "2026-07-19";
  };
  searxng-doubao-bridge = {
    pname = "searxng-doubao-bridge";
    version = "72e59326cd34d94f47a632c3a4e692aea7d84ffc";
    src = fetchgit {
      url = "https://github.com/p3psi-boo/searxng-doubao-bridge.git";
      rev = "72e59326cd34d94f47a632c3a4e692aea7d84ffc";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-CfBX/IonAHjO+IEZs3/NSkG72t4vfjFCh2CMfuQVxhk=";
    };
    date = "2026-07-19";
  };
  selector4nix = {
    pname = "selector4nix";
    version = "v0.9.0";
    src = fetchFromGitHub {
      owner = "StarryReverie";
      repo = "selector4nix";
      rev = "v0.9.0";
      fetchSubmodules = false;
      sha256 = "sha256-zWpQBvTrE18lQvTErj/fJMLssrSgrbzTLVto/j78qqg=";
    };
  };

  sofixer = {
    pname = "sofixer";
    version = "v2.1.7";
    src = fetchFromGitHub {
      owner = "F8LEFT";
      repo = "SoFixer";
      rev = "v2.1.7";
      fetchSubmodules = false;
      sha256 = "sha256-emvN0iNPoADAiH4eOPCIViNHpItKyacySu/9EK2BaeQ=";
    };
  };
  srv-us = {
    pname = "srv-us";
    version = "664ef6a4fab24c5f3f1fc2fa07cc3e0c43d90cf9";
    src = fetchgit {
      url = "https://github.com/p3psi-boo/srv.us.git";
      rev = "664ef6a4fab24c5f3f1fc2fa07cc3e0c43d90cf9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-CEaSHwR8munYwKkLkCAGGbnRsel+by72QBY28lIRQO4=";
    };
    date = "2026-02-08";
  };
  subs-check = {
    pname = "subs-check";
    version = "753fe79b88d07eea1affb141174344113d5825d6";
    src = fetchgit {
      url = "https://github.com/p3psi-boo/subs-check.git";
      rev = "753fe79b88d07eea1affb141174344113d5825d6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-oU1nqg6SPjRZCmG7jN0r87qEX5NJEuFOq700WSw6i/8=";
    };
    date = "2026-07-05";
  };

  sugar-wifi-conf = {
    pname = "sugar-wifi-conf";
    version = "956d493be87b928688bd08a87f5851fb8ef0fcba";
    src = fetchgit {
      url = "https://github.com/PiSugar/sugar-wifi-conf.git";
      rev = "956d493be87b928688bd08a87f5851fb8ef0fcba";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-tHVVCq+qSeLFwpH8sGsAi92pr2HU60o6Hdm+PNokfbk=";
    };
    date = "2026-08-03";
  };

  terminal-use = {
    pname = "terminal-use";
    version = "v1.2.0";
    src = fetchFromGitHub {
      owner = "flipbit03";
      repo = "terminal-use";
      rev = "v1.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-wHu+L//x1NiXTxD2mas0niV/TbTezg4MC7wUWAfgxpY=";
    };
  };

  usque = {
    pname = "usque";
    version = "6aa03fc97d12848dce34eedbd187fb1077b5d1ea";
    src = fetchgit {
      url = "https://github.com/Diniboy1123/usque.git";
      rev = "6aa03fc97d12848dce34eedbd187fb1077b5d1ea";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-aUAji41gVsRs47IDtLAinxUZsZjTQvO/SMWe5GdmJLw=";
    };
    date = "2026-07-20";
  };

  vja = {
    pname = "vja";
    version = "1bbea5452dae7a7ee97c2b9b3317fc989a4cf3ea";
    src = fetchgit {
      url = "https://github.com/p3psi-boo/vikunja-cli.git";
      rev = "1bbea5452dae7a7ee97c2b9b3317fc989a4cf3ea";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-cDEquvuDHqz2bm9oecHWvTyB2fop6ORgPu8GQ3t2xNE=";
    };
    date = "2026-06-28";
  };
  vohive = {
    pname = "vohive";
    version = "6f8bc6ff7b0f644f939a4a2f1d8a748b74174473";
    src = fetchgit {
      url = "https://github.com/p3psi-boo/vohive.git";
      rev = "6f8bc6ff7b0f644f939a4a2f1d8a748b74174473";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ng8l/4FfuEgW6QIJFlD62XYXG00/mVdnEbTvdDZN7SA=";
    };
    date = "2026-08-06";
  };

  wikiteam3 = {
    pname = "wikiteam3";
    version = "317f63f69d0f136783f95d0d54e7e03bf4d483dd";
    src = fetchgit {
      url = "https://github.com/saveweb/wikiteam3.git";
      rev = "317f63f69d0f136783f95d0d54e7e03bf4d483dd";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-QE6XPxAe1cRQWWawhRZiyXwS/VDm+Ybze8eNcgDyLAg=";
    };
    date = "2026-08-10";
  };

  wxmp_searxng = {
    pname = "wxmp_searxng";
    version = "edb809f0c67238e26caae840fd3ef7ff653792b3";
    src = fetchgit {
      url = "https://github.com/p3psi-boo/wxmp_searxng.git";
      rev = "edb809f0c67238e26caae840fd3ef7ff653792b3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Y9QqZZVZ+LaWA5I9it5VxgW8fIt3c2EP2KaNob49uIU=";
    };
    date = "2026-07-12";
  };

}
