# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  activitywatch-bin = {
    pname = "activitywatch-bin";
    version = "v0.14.0b8";
    src = fetchurl {
      url = "https://github.com/ActivityWatch/activitywatch/releases/download/v0.14.0b8/activitywatch-v0.14.0b8-macos-arm64.dmg";
      sha256 = "sha256-BrT1I++dfGPb5UwYNuKKGa7GjjUOrShVpYEMM/Sk8CY=";
    };
  };
  agentreach = {
    pname = "agentreach";
    version = "v0.8.0";
    src = fetchFromGitHub {
      owner = "bojieli";
      repo = "agentreach";
      rev = "v0.8.0";
      fetchSubmodules = false;
      sha256 = "sha256-PL+YtRf+5L2j7WgpDNQn4DssPwGbA95iWKqNJ+U3FME=";
    };
  };
  aw-watcher-herdr = {
    pname = "aw-watcher-herdr";
    version = "1ad7e9a40c245c60e5b12c47ff98f4c5b5439ab2";
    src = fetchFromGitHub {
      owner = "p3psi-boo";
      repo = "aw-watcher-herdr";
      rev = "1ad7e9a40c245c60e5b12c47ff98f4c5b5439ab2";
      fetchSubmodules = false;
      sha256 = "sha256-ce0h3Wn6/95buJTJgCmBUwbA8ISxQbhqrIOmmYWc8oE=";
    };
    date = "2026-10-01";
  };
  celld = {
    pname = "celld";
    version = "v0.6.1";
    src = fetchFromGitHub {
      owner = "denoland";
      repo = "celld";
      rev = "v0.6.1";
      fetchSubmodules = false;
      sha256 = "sha256-/bGMzxYiIh82AeTKhbtIeWF1UlIknIxH0YpI4H18Wws=";
    };
  };
  cliproxyapi = {
    pname = "cliproxyapi";
    version = "v8.0.16";
    src = fetchFromGitHub {
      owner = "router-for-me";
      repo = "CLIProxyAPI";
      rev = "v8.0.16";
      fetchSubmodules = false;
      sha256 = "sha256-eBWqOqWkvaONEut28hUHOmuc4JcZBp2SCEnXT2CAxS4=";
    };
  };
  cloakbrowser = {
    pname = "cloakbrowser";
    version = "146.0.7680.177.5";
    src = fetchurl {
      url = "https://cloakbrowser.dev/chromium-v146.0.7680.177.5/cloakbrowser-linux-x64.tar.gz";
      sha256 = "sha256-ShK83pX6G7G+7ytBq15cJ8Nr544749DayMZNcFIWZw4=";
    };
  };
  cmcc-ec-keepalive = {
    pname = "cmcc-ec-keepalive";
    version = "dae23c54a6eb1057c4a016914347f0abdd6fd163";
    src = fetchFromGitHub {
      owner = "p3psi-boo";
      repo = "cmcc-ec-keepalive";
      rev = "dae23c54a6eb1057c4a016914347f0abdd6fd163";
      fetchSubmodules = false;
      sha256 = "sha256-9L9c68TkiUHgnPJyFQiXVfLSsSEiEXDPpg7zyV0EVxQ=";
    };
    date = "2026-08-20";
  };
  codex-auth = {
    pname = "codex-auth";
    version = "v0.3.0";
    src = fetchFromGitHub {
      owner = "loongphy";
      repo = "codex-auth";
      rev = "v0.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-TrJtVP4gRdupx6StKWc2PIXoVnnlFMUqFw6JtEmWqZ4=";
    };
  };
  coe = {
    pname = "coe";
    version = "c326261675a2455e6dd8c22576681e91644600ef";
    src = fetchgit {
      url = "https://github.com/p3psi-boo/coe.git";
      rev = "c326261675a2455e6dd8c22576681e91644600ef";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-0VL8NsKi1zl8fWJHn9khUwb0Jx0NIEvAdqe7slSfPyw=";
    };
    date = "2026-04-23";
  };
  commandcode2api = {
    pname = "commandcode2api";
    version = "1010b2292ebd626d16662f878350e173286110c2";
    src = fetchgit {
      url = "https://github.com/p3psi-boo/commandcode2api.git";
      rev = "1010b2292ebd626d16662f878350e173286110c2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-rMry5ozjcwK044CivmqEwTUajKId2PYIs3NOGjh0gjk=";
    };
    date = "2026-08-15";
  };
  cookiecloud-rs = {
    pname = "cookiecloud-rs";
    version = "f8a023f42951c8ba97261d3b16e3a4ff53c91f4a";
    src = fetchgit {
      url = "https://github.com/p3psi-boo/CookieCloud.git";
      rev = "f8a023f42951c8ba97261d3b16e3a4ff53c91f4a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ak78lDOAaDWCk9dNpQ9nNObwXrhj71umhzu01hagt2I=";
    };
    date = "2026-04-14";
  };
  couic = {
    pname = "couic";
    version = "v1.0.2";
    src = fetchFromGitHub {
      owner = "FCSC-FR";
      repo = "couic";
      rev = "v1.0.2";
      fetchSubmodules = false;
      sha256 = "sha256-84mMlLC/zEg4rYJ1Ag3PHmj4LZ0CNI5QCq4Uc9A1IMk=";
    };
  };
  dagu-aarch64-darwin = {
    pname = "dagu-aarch64-darwin";
    version = "2.18.2";
    src = fetchurl {
      url = "https://github.com/dagucloud/dagu/releases/download/v2.18.2/dagu_2.18.2_darwin_arm64.tar.gz";
      sha256 = "sha256-9piH01x2XYBRTHZEGZpWPVtq9xmLuXeY6MiiWFgJG+w=";
    };
  };
  dagu-aarch64-linux = {
    pname = "dagu-aarch64-linux";
    version = "2.18.2";
    src = fetchurl {
      url = "https://github.com/dagucloud/dagu/releases/download/v2.18.2/dagu_2.18.2_linux_arm64.tar.gz";
      sha256 = "sha256-9nxj7zQ7EaaCL4gTSM8f8nooyX6i7iZ/IahzZKkKHcU=";
    };
  };
  dagu-x86_64-darwin = {
    pname = "dagu-x86_64-darwin";
    version = "2.18.2";
    src = fetchurl {
      url = "https://github.com/dagucloud/dagu/releases/download/v2.18.2/dagu_2.18.2_darwin_amd64.tar.gz";
      sha256 = "sha256-n6UOIbOp/6y+RPH+JoHUyE6TAf9FA2UlEDZ2F2nPCcY=";
    };
  };
  dagu-x86_64-linux = {
    pname = "dagu-x86_64-linux";
    version = "2.18.2";
    src = fetchurl {
      url = "https://github.com/dagucloud/dagu/releases/download/v2.18.2/dagu_2.18.2_linux_amd64.tar.gz";
      sha256 = "sha256-WoTAk7m6nQK3pg4Qa7kdRvk4P9AcYr1RVg5BGT8FeSs=";
    };
  };
  einat = {
    pname = "einat";
    version = "ba647ce61bd6bdf2cb693961a82b88c442ef049a";
    src = fetchgit {
      url = "https://github.com/EHfive/einat-ebpf.git";
      rev = "ba647ce61bd6bdf2cb693961a82b88c442ef049a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-/Q95r3z67tcuChrYv3uBXzbablopLZNfzZHhsl1y2eQ=";
    };
    date = "2026-09-20";
  };
  firefox-vpn-client = {
    pname = "firefox-vpn-client";
    version = "5b29eebc2766ac1cac2979693c56a8dfbad32430";
    src = fetchFromGitHub {
      owner = "UjuiUjuMandan";
      repo = "firefox-vpn-client";
      rev = "5b29eebc2766ac1cac2979693c56a8dfbad32430";
      fetchSubmodules = false;
      sha256 = "sha256-0TNJLbyQDipIb89anIhPHFmZrD1XXZl643JkgbzWVx4=";
    };
    date = "2026-08-22";
  };
  focaltech-fingerprint = {
    pname = "focaltech-fingerprint";
    version = "510473c10a16ff37820b2db1d8ef2d2b08ad005d";
    src = fetchgit {
      url = "https://github.com/vobademi/FTEXX00-Ubuntu.git";
      rev = "510473c10a16ff37820b2db1d8ef2d2b08ad005d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-v1CzRLZ4u+zdQXezt9rVy63RMp1gM/id1S7bRwcBDEA=";
    };
    date = "2026-09-17";
  };
  fusion = {
    pname = "fusion";
    version = "ecc44eeff94dd4836eed6490a497989194effa2b";
    src = fetchgit {
      url = "https://github.com/p3psi-boo/fusion.git";
      rev = "ecc44eeff94dd4836eed6490a497989194effa2b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-O9NMromcyvcF97Kb084vrHPjqRgyRqq14Ay8pdsj9rQ=";
    };
    date = "2026-04-12";
  };
  herdr-git = {
    pname = "herdr-git";
    version = "3d9d2b18dab139ba226ebc5a1c9a9f2c9c3ee4df";
    src = fetchFromGitHub {
      owner = "herdrdev";
      repo = "herdr";
      rev = "3d9d2b18dab139ba226ebc5a1c9a9f2c9c3ee4df";
      fetchSubmodules = false;
      sha256 = "sha256-z1i72jg4QeR8+tQGaOalCT/jHxgbg3fTO9Y0EjWKWTQ=";
    };
    date = "2026-10-06";
  };
  icloud-privacy-mail-v2 = {
    pname = "icloud-privacy-mail-v2";
    version = "4ec96e0ea1e026b81c7efa03db19332790f02e64";
    src = fetchFromGitHub {
      owner = "xiuxiu56";
      repo = "iCloud-Privacy-Mail-v2";
      rev = "4ec96e0ea1e026b81c7efa03db19332790f02e64";
      fetchSubmodules = false;
      sha256 = "sha256-LcTnIcv5il3Go9nFUhFJbp5euGtMmqZ8smso7ALFNRY=";
    };
    date = "2026-08-29";
  };
  komari = {
    pname = "komari";
    version = "39cb3f59b2837e8d052203bfbbf3187888e5fa4c";
    src = fetchgit {
      url = "https://github.com/komari-monitor/komari.git";
      rev = "39cb3f59b2837e8d052203bfbbf3187888e5fa4c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Wlrfp0MyI9cut2lsoMtzfARRUsm3TDQCUxWbnNahkPk=";
    };
    date = "2026-09-28";
  };
  komari-agent-zig = {
    pname = "komari-agent-zig";
    version = "28a96ce98ce81d6c2aa4e1a33d74bfcf7dbc4fd1";
    src = fetchgit {
      url = "https://github.com/luodaoyi/komari-zig-agent.git";
      rev = "28a96ce98ce81d6c2aa4e1a33d74bfcf7dbc4fd1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-RX8XfZaYlGGzo3TZQV/2HPlPkhDTk4Rg/TWgrIPZHoA=";
    };
    date = "2026-09-30";
  };
  komari-web = {
    pname = "komari-web";
    version = "0321789bc1989e53df729dfc98bed2a2800c39c6";
    src = fetchgit {
      url = "https://github.com/komari-monitor/komari-web.git";
      rev = "0321789bc1989e53df729dfc98bed2a2800c39c6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ZJn+Grwfg2p813QQ87w39xk4lEbQsT/SbCal8lIcd3o=";
    };
    date = "2026-09-24";
  };
  latch = {
    pname = "latch";
    version = "a980512b8f1a56d2f462b81b17a8fcae2c46ccf9";
    src = fetchFromGitHub {
      owner = "p3psi-boo";
      repo = "latch";
      rev = "a980512b8f1a56d2f462b81b17a8fcae2c46ccf9";
      fetchSubmodules = false;
      sha256 = "sha256-/QaHe8HSlv7TQgsp1V/brnx9ntPNJG2HpB6le8zWq18=";
    };
    date = "2026-10-09";
  };
  lazyssh = {
    pname = "lazyssh";
    version = "48995806bf1aa1c9c41bb8dff6b5ddd698539311";
    src = fetchgit {
      url = "https://github.com/p3psi-boo/lazyssh.git";
      rev = "48995806bf1aa1c9c41bb8dff6b5ddd698539311";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-/jywzjLZ51nSbiDbhw3H1eES3p0sZ9MSayGjJFQ+RKM=";
    };
    date = "2025-11-28";
  };
  linear-cli = {
    pname = "linear-cli";
    version = "v2.6.0";
    src = fetchFromGitHub {
      owner = "schpet";
      repo = "linear-cli";
      rev = "v2.6.0";
      fetchSubmodules = false;
      sha256 = "sha256-wInqzwamLoWgIU6qDaOjgblBuqUJRQmhs5xg4+Npabo=";
    };
  };
  mcpjungle = {
    pname = "mcpjungle";
    version = "9512d31382b6b14edc6f98931537de5c137bc6b8";
    src = fetchFromGitHub {
      owner = "p3psi-boo";
      repo = "MCPJungle";
      rev = "9512d31382b6b14edc6f98931537de5c137bc6b8";
      fetchSubmodules = false;
      sha256 = "sha256-m/ChdIBiteyYTvfu4pGZpS+ABhvoYyqHMDQbNhhgUzQ=";
    };
    date = "2026-10-08";
  };
  mebox = {
    pname = "mebox";
    version = "mebox-v0.1.182";
    src = fetchFromGitHub {
      owner = "truewhile";
      repo = "MeBox";
      rev = "mebox-v0.1.182";
      fetchSubmodules = false;
      sha256 = "sha256-htEh4OUX5J204dViQwHVjzklSN/lVf8wieWbLptants=";
    };
  };
  micyou = {
    pname = "micyou";
    version = "v2.1.0";
    src = fetchFromGitHub {
      owner = "LanRhyme";
      repo = "MicYou";
      rev = "v2.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-OoIamslISIxH1VNTOmKqyibJWUQelOL/fcUHxywTEzY=";
    };
  };
  n9router = {
    pname = "n9router";
    version = "647ddecea0eb7abf67ae70284e762f9593c67da8";
    src = fetchgit {
      url = "https://github.com/nightwalker89/n9router.git";
      rev = "647ddecea0eb7abf67ae70284e762f9593c67da8";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-dERlmXHbHatS+8CS13MdLnYuk1WPqglxfnTOq6kbU/A=";
    };
    date = "2026-09-22";
  };
  nmem-cli = {
    pname = "nmem-cli";
    version = "0.10.88";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/py3/n/nmem-cli/nmem_cli-0.10.88-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl";
      sha256 = "sha256-TkWc37D+NMn5uO+c3nVk9KfmCMP4At65/MQkSwNc+n8=";
    };
  };
  nmem-cli-aarch64-darwin = {
    pname = "nmem-cli-aarch64-darwin";
    version = "0.10.88";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/py3/n/nmem-cli/nmem_cli-0.10.88-py3-none-macosx_11_0_arm64.whl";
      sha256 = "sha256-juFZ/sp/5PmEa4pwGgLXZashI6eAUmTqlrxBzFgYtNo=";
    };
  };
  nmem-cli-aarch64-linux = {
    pname = "nmem-cli-aarch64-linux";
    version = "0.10.88";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/py3/n/nmem-cli/nmem_cli-0.10.88-py3-none-manylinux_2_17_aarch64.manylinux2014_aarch64.whl";
      sha256 = "sha256-pDrr1HN3j9/9Y6jyM7Pm72FkRJfTOnSgPmwTouTvIXc=";
    };
  };
  nmem-cli-x86_64-darwin = {
    pname = "nmem-cli-x86_64-darwin";
    version = "0.10.88";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/py3/n/nmem-cli/nmem_cli-0.10.88-py3-none-macosx_10_12_x86_64.whl";
      sha256 = "sha256-lRr9sBu04g+EoQ4Z699aNR7YpeHLgcPdDAuV8gMlky0=";
    };
  };
  octopus-api = {
    pname = "octopus-api";
    version = "7b7a4801fa501f9244a1d9dfb47da56d1600b970";
    src = fetchgit {
      url = "https://github.com/p3psi-boo/octopus.git";
      rev = "7b7a4801fa501f9244a1d9dfb47da56d1600b970";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-pwKEYRAPnPwElyFhh4tI+vVV/BMLLCFnFIpgotMd0Wc=";
    };
    date = "2026-08-06";
  };
  picoclaw = {
    pname = "picoclaw";
    version = "v0.3.1";
    src = fetchFromGitHub {
      owner = "sipeed";
      repo = "picoclaw";
      rev = "v0.3.1";
      fetchSubmodules = false;
      sha256 = "sha256-QYfHXIHJjeZJdkhGNNhdO91Q8EFgSP+ubqGJ8VgTEtc=";
    };
  };
  piko = {
    pname = "piko";
    version = "v0.1.5";
    src = fetchFromGitHub {
      owner = "UruhaLushia";
      repo = "piko";
      rev = "v0.1.5";
      fetchSubmodules = false;
      sha256 = "sha256-36JrU8a+XUUUiQT39x9495/xk1zjP1q+OlMcR7ZPq9o=";
    };
  };
  proxy-ns = {
    pname = "proxy-ns";
    version = "5d08d18f9171d7e65fabad06ee81021d9bca0a21";
    src = fetchgit {
      url = "https://github.com/OkamiW/proxy-ns.git";
      rev = "5d08d18f9171d7e65fabad06ee81021d9bca0a21";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-4w5aiVpbmlGkCyg5YQnjXYkdgrbZADiWw+l4kd6ecek=";
    };
    date = "2026-04-09";
  };
  sdbd = {
    pname = "sdbd";
    version = "0a0a15b694108328be1ede66ee32f6acbd95d3d7";
    src = fetchFromGitHub {
      owner = "openbfdev";
      repo = "sdbd";
      rev = "0a0a15b694108328be1ede66ee32f6acbd95d3d7";
      fetchSubmodules = false;
      sha256 = "sha256-5tHq2nFl1IKfx2iHLxzbMl7wtCe/zkcmQa3nfXTaBss=";
    };
    date = "2025-04-03";
  };
  searxng-baidu-qianfan-bridge = {
    pname = "searxng-baidu-qianfan-bridge";
    version = "a9826ab251fa3d52a59a3900f702ab53cd602793";
    src = fetchgit {
      url = "https://github.com/p3psi-boo/searxng-baidu-qianfan-bridge.git";
      rev = "a9826ab251fa3d52a59a3900f702ab53cd602793";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-oaPrdnj4OBjTyxeMKDVBpxzbGMoSQjLc1lvbRdLCeCs=";
    };
    date = "2026-07-19";
  };
  searxng-doubao-bridge = {
    pname = "searxng-doubao-bridge";
    version = "72e59326cd34d94f47a632c3a4e692aea7d84ffc";
    src = fetchgit {
      url = "https://github.com/p3psi-boo/searxng-doubao-bridge.git";
      rev = "72e59326cd34d94f47a632c3a4e692aea7d84ffc";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-CfBX/IonAHjO+IEZs3/NSkG72t4vfjFCh2CMfuQVxhk=";
    };
    date = "2026-07-19";
  };
  selector4nix = {
    pname = "selector4nix";
    version = "95367eb7a98ae6ba52573e1ae3e299429f1a5a8b";
    src = fetchgit {
      url = "https://github.com/p3psi-boo/selector4nix.git";
      rev = "95367eb7a98ae6ba52573e1ae3e299429f1a5a8b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-X1ua1JFrA74Y3VW62sDx1B51uwCO1/ANjiNLywrNDFc=";
    };
    date = "2026-09-12";
  };
  sing-box-tui = {
    pname = "sing-box-tui";
    version = "7e8af45bd52d371332524a110518cf04edbd2bdf";
    src = fetchgit {
      url = "https://github.com/p3psi-boo/sing-box-tui.git";
      rev = "7e8af45bd52d371332524a110518cf04edbd2bdf";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-hOiqv+mwrtKzI5JjXwbKQ95uw5IGGc20pKiz2Vls/jA=";
    };
    date = "2026-10-09";
  };
  sofixer = {
    pname = "sofixer";
    version = "v2.1.7";
    src = fetchFromGitHub {
      owner = "F8LEFT";
      repo = "SoFixer";
      rev = "v2.1.7";
      fetchSubmodules = false;
      sha256 = "sha256-emvN0iNPoADAiH4eOPCIViNHpItKyacySu/9EK2BaeQ=";
    };
  };
  srv-us = {
    pname = "srv-us";
    version = "664ef6a4fab24c5f3f1fc2fa07cc3e0c43d90cf9";
    src = fetchgit {
      url = "https://github.com/p3psi-boo/srv.us.git";
      rev = "664ef6a4fab24c5f3f1fc2fa07cc3e0c43d90cf9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-CEaSHwR8munYwKkLkCAGGbnRsel+by72QBY28lIRQO4=";
    };
    date = "2026-02-08";
  };
  subs-check = {
    pname = "subs-check";
    version = "753fe79b88d07eea1affb141174344113d5825d6";
    src = fetchgit {
      url = "https://github.com/p3psi-boo/subs-check.git";
      rev = "753fe79b88d07eea1affb141174344113d5825d6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-oU1nqg6SPjRZCmG7jN0r87qEX5NJEuFOq700WSw6i/8=";
    };
    date = "2026-07-05";
  };
  sugar-wifi-conf = {
    pname = "sugar-wifi-conf";
    version = "956d493be87b928688bd08a87f5851fb8ef0fcba";
    src = fetchgit {
      url = "https://github.com/PiSugar/sugar-wifi-conf.git";
      rev = "956d493be87b928688bd08a87f5851fb8ef0fcba";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-tHVVCq+qSeLFwpH8sGsAi92pr2HU60o6Hdm+PNokfbk=";
    };
    date = "2026-08-03";
  };
  taierspeedtest = {
    pname = "taierspeedtest";
    version = "v1.0.3";
    src = fetchFromGitHub {
      owner = "MiaM1ku";
      repo = "taierspeedtest";
      rev = "v1.0.3";
      fetchSubmodules = false;
      sha256 = "sha256-jITzS2zDqadmt8XRWVio2u/T9vDrb/AAhNJHTnFVEHw=";
    };
  };
  terminal-use = {
    pname = "terminal-use";
    version = "v1.4.1";
    src = fetchFromGitHub {
      owner = "flipbit03";
      repo = "terminal-use";
      rev = "v1.4.1";
      fetchSubmodules = false;
      sha256 = "sha256-x4wK6Vw7qMkRYRRqgaNvUh8lSngodw4nX/BUzmqOtmU=";
    };
  };
  vja = {
    pname = "vja";
    version = "1bbea5452dae7a7ee97c2b9b3317fc989a4cf3ea";
    src = fetchgit {
      url = "https://github.com/p3psi-boo/vikunja-cli.git";
      rev = "1bbea5452dae7a7ee97c2b9b3317fc989a4cf3ea";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-cDEquvuDHqz2bm9oecHWvTyB2fop6ORgPu8GQ3t2xNE=";
    };
    date = "2026-06-28";
  };
  vohive = {
    pname = "vohive";
    version = "6f8bc6ff7b0f644f939a4a2f1d8a748b74174473";
    src = fetchgit {
      url = "https://github.com/p3psi-boo/vohive.git";
      rev = "6f8bc6ff7b0f644f939a4a2f1d8a748b74174473";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ng8l/4FfuEgW6QIJFlD62XYXG00/mVdnEbTvdDZN7SA=";
    };
    date = "2026-08-06";
  };
  wallos-mcp = {
    pname = "wallos-mcp";
    version = "179f02d7c39c2d73ad00d6ace080c993290ea94f";
    src = fetchFromGitHub {
      owner = "p3psi-boo";
      repo = "wallos-mcp";
      rev = "179f02d7c39c2d73ad00d6ace080c993290ea94f";
      fetchSubmodules = false;
      sha256 = "sha256-k20pim5Cs50gicrh18REDj738tfq5Nh+0ZAgcvWx9MQ=";
    };
    date = "2026-10-07";
  };
  wxmp_searxng = {
    pname = "wxmp_searxng";
    version = "edb809f0c67238e26caae840fd3ef7ff653792b3";
    src = fetchgit {
      url = "https://github.com/p3psi-boo/wxmp_searxng.git";
      rev = "edb809f0c67238e26caae840fd3ef7ff653792b3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Y9QqZZVZ+LaWA5I9it5VxgW8fIt3c2EP2KaNob49uIU=";
    };
    date = "2026-07-12";
  };
}
