# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  agsh = {
    pname = "agsh";
    version = "0.11.0";
    src = fetchFromGitHub {
      owner = "k4yt3x";
      repo = "agsh";
      rev = "0.11.0";
      fetchSubmodules = false;
      sha256 = "sha256-bFPhf3p6W7tnQzno/kYVYZkO26R0JvcJHbpvNOmhlx4=";
    };
  };
  bb-browser = {
    pname = "bb-browser";
    version = "bb-browser-v0.11.2";
    src = fetchFromGitHub {
      owner = "epiral";
      repo = "bb-browser";
      rev = "bb-browser-v0.11.2";
      fetchSubmodules = false;
      sha256 = "sha256-DoAd8oN4Il5xGHkcDKgmLczUYj0D0PvxhbSmnDYb+wI=";
    };
  };
  bcut-asr = {
    pname = "bcut-asr";
    version = "07fc48213a415490da1ae40cd8988a087cb02ec6";
    src = fetchgit {
      url = "https://github.com/p3psi-boo/bcut-asr-go.git";
      rev = "07fc48213a415490da1ae40cd8988a087cb02ec6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-uGhqogSabFpuWQ1h88oXrCOPuJPyfuR9nx8Ug5WbUl0=";
    };
    date = "2026-01-14";
  };
  binsider-bin = {
    pname = "binsider-bin";
    version = "0.3.2";
    src = fetchurl {
      url = "https://github.com/orhun/binsider/releases/download/v0.3.2/binsider-0.3.2-x86_64-unknown-linux-musl.tar.gz";
      sha256 = "sha256-/TScWAgk8rUv981qMCqqd0o/5L7t2TeFFb3+zsDYd6M=";
    };
  };
  binsider-bin-aarch64-linux = {
    pname = "binsider-bin-aarch64-linux";
    version = "0.3.2";
    src = fetchurl {
      url = "https://github.com/orhun/binsider/releases/download/v0.3.2/binsider-0.3.2-aarch64-unknown-linux-musl.tar.gz";
      sha256 = "sha256-pedF8eMfFmfsFPYjm6w8McxQQ5YmJLEtrkGC0xtSROI=";
    };
  };
  binsider-bin-darwin-arm64 = {
    pname = "binsider-bin-darwin-arm64";
    version = "0.3.2";
    src = fetchurl {
      url = "https://github.com/orhun/binsider/releases/download/v0.3.2/binsider-0.3.2-aarch64-apple-darwin.tar.gz";
      sha256 = "sha256-CNYBoXtsEpvWzXGqp2+loZT88hgVzLocm//4tklnT78=";
    };
  };
  binsider-bin-darwin-x64 = {
    pname = "binsider-bin-darwin-x64";
    version = "0.3.2";
    src = fetchurl {
      url = "https://github.com/orhun/binsider/releases/download/v0.3.2/binsider-0.3.2-x86_64-apple-darwin.tar.gz";
      sha256 = "sha256-HDz+JDAf3WeezxZTeLsTNb9kAdAHfPOxu6/lkchG6Bo=";
    };
  };
  bird-cli = {
    pname = "bird-cli";
    version = "c815bfbe3cefd0104adf411cd2148995c31f2ba0";
    src = fetchgit {
      url = "https://github.com/p3psi-boo/bird-fork.git";
      rev = "c815bfbe3cefd0104adf411cd2148995c31f2ba0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-47N0//wE3G9RGrcSa0JJTnu9mbw/MK58PNnuqYyitvw=";
    };
    date = "2026-03-09";
  };
  classyshark = {
    pname = "classyshark";
    version = "8.2";
    src = fetchFromGitHub {
      owner = "google";
      repo = "android-classyshark";
      rev = "8.2";
      fetchSubmodules = false;
      sha256 = "sha256-9gENYNWfbPK2jpxiHOf8ETJwXqjFMgplaHNkO3ohhDQ=";
    };
  };
  clihub = {
    pname = "clihub";
    version = "v0.0.8";
    src = fetchFromGitHub {
      owner = "thellimist";
      repo = "clihub";
      rev = "v0.0.8";
      fetchSubmodules = false;
      sha256 = "sha256-Y/O2XmhMYUCV269g+h+DsQT80yVR0ot9RIS+mBJP7BA=";
    };
  };
  clipboard-sync = {
    pname = "clipboard-sync";
    version = "0.2.0";
    src = fetchFromGitHub {
      owner = "dnut";
      repo = "clipboard-sync";
      rev = "0.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-gme5pwQrwQbk8MroF/mGYqlY6hcjM5cHKHL7Y3nlW9k=";
    };
  };
  cliproxyapi = {
    pname = "cliproxyapi";
    version = "v6.9.28";
    src = fetchFromGitHub {
      owner = "router-for-me";
      repo = "CLIProxyAPI";
      rev = "v6.9.28";
      fetchSubmodules = false;
      sha256 = "sha256-TBSYsH6CW11mQN4Z8Q9wf7piZiggOio8eSejnYUj2Ro=";
    };
  };
  cloudflarespeedtest = {
    pname = "cloudflarespeedtest";
    version = "v2.3.4";
    src = fetchFromGitHub {
      owner = "XIU2";
      repo = "CloudflareSpeedTest";
      rev = "v2.3.4";
      fetchSubmodules = false;
      sha256 = "sha256-ZrBRHJsVHuTjftMcxpk+p2Z/wm49DmIaO/w0bjQ9ROo=";
    };
  };
  cnb-cli = {
    pname = "cnb-cli";
    version = "4fb4e70a616a809755f2feefda1aee50ff88450e";
    src = fetchgit {
      url = "https://github.com/p3psi-boo/cnb-cli.git";
      rev = "4fb4e70a616a809755f2feefda1aee50ff88450e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-0Yqn/akLsksS3Z6WBx3jZ9pG0n/lgLQSK8Z3iWfZkuA=";
    };
    date = "2026-02-26";
  };
  cocoindex-code = {
    pname = "cocoindex-code";
    version = "0.2.27";
    src = fetchurl {
      url = "https://github.com/cocoindex-io/cocoindex-code/archive/refs/tags/v0.2.27.tar.gz";
      sha256 = "sha256-QmPnOBqFsDn4raBgmTYWq8P2JHVp96KKax8cQAu95xY=";
    };
  };
  coe = {
    pname = "coe";
    version = "8ce49ed06b88dc610d34b04acfd03bfdc0f78787";
    src = fetchgit {
      url = "https://github.com/p3psi-boo/coe.git";
      rev = "8ce49ed06b88dc610d34b04acfd03bfdc0f78787";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-I1KFljvfmZ2pwOvqSMrvO6rZfvdA6xrFR2j8eEkgq94=";
    };
    date = "2026-04-02";
  };
  cookiecloud-rs = {
    pname = "cookiecloud-rs";
    version = "f8a023f42951c8ba97261d3b16e3a4ff53c91f4a";
    src = fetchgit {
      url = "https://github.com/p3psi-boo/CookieCloud.git";
      rev = "f8a023f42951c8ba97261d3b16e3a4ff53c91f4a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ak78lDOAaDWCk9dNpQ9nNObwXrhj71umhzu01hagt2I=";
    };
    date = "2026-04-14";
  };
  copilot-api-plus = {
    pname = "copilot-api-plus";
    version = "446b562090d22dbaa96ceaf776e70e29757005ba";
    src = fetchgit {
      url = "https://github.com/imbuxiangnan-cyber/copilot-api-plus.git";
      rev = "446b562090d22dbaa96ceaf776e70e29757005ba";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-TNr1leik1h6PiSdFDUPxr4ucNYSB7THO4LMvCUSvzUY=";
    };
    date = "2026-04-17";
  };
  dagu = {
    pname = "dagu";
    version = "v2.5.0";
    src = fetchFromGitHub {
      owner = "dagu-org";
      repo = "dagu";
      rev = "v2.5.0";
      fetchSubmodules = false;
      sha256 = "sha256-zI/SD+uz6lO5woHUCDawaLtOZ0fS8efSaZSh6MTuB5k=";
    };
  };
  dalvikus = {
    pname = "dalvikus";
    version = "1.0.13";
    src = fetchurl {
      url = "https://github.com/loerting/dalvikus/archive/refs/tags/v1.0.13.tar.gz";
      sha256 = "sha256-PMSalWlMDIqMWgPZ6Ha7L6TA2VOX6svCAOYMSpzIqHY=";
    };
  };
  dbhub = {
    pname = "dbhub";
    version = "0.21.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/@bytebase/dbhub/-/dbhub-0.21.2.tgz";
      sha256 = "sha256-eOwzRCZAYypW/GY1zXIqusads2xEv50s01xhfroZPTo=";
    };
  };
  ecloud-computer-auto-boot = {
    pname = "ecloud-computer-auto-boot";
    version = "1.0.0";
    src = fetchFromGitHub {
      owner = "Samler-Lee";
      repo = "ecloud_computer_auto_boot";
      rev = "1.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-9H11Jli1Ls8FNtvfgt5X+1yEw4zcrqcmBWPdyq8TIf8=";
    };
  };
  einat = {
    pname = "einat";
    version = "b226ff98856e59be7f091bc7d81ceba8ac38bd19";
    src = fetchgit {
      url = "https://github.com/EHfive/einat-ebpf.git";
      rev = "b226ff98856e59be7f091bc7d81ceba8ac38bd19";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-P0Q8DdeEns5xcALj5vIyubc1AE073nozbNoTzRso37w=";
    };
    date = "2025-12-11";
  };
  fff-mcp = {
    pname = "fff-mcp";
    version = "0.5.2";
    src = fetchurl {
      url = "https://github.com/dmtrKovalenko/fff.nvim/releases/download/v0.5.2/fff-mcp-x86_64-unknown-linux-musl";
      sha256 = "sha256-o7AoV75bm6mR4bn7nmvbA7dCEtpEe2IbuwKEN0g8NJo=";
    };
  };
  fff-mcp-aarch64-linux = {
    pname = "fff-mcp-aarch64-linux";
    version = "0.5.2";
    src = fetchurl {
      url = "https://github.com/dmtrKovalenko/fff.nvim/releases/download/v0.5.2/fff-mcp-aarch64-unknown-linux-musl";
      sha256 = "sha256-MdDeiUghB2unOdzSA7zxpB+CRCbGGm9iO0iWfwgDHeY=";
    };
  };
  fff-mcp-darwin-arm64 = {
    pname = "fff-mcp-darwin-arm64";
    version = "0.5.2";
    src = fetchurl {
      url = "https://github.com/dmtrKovalenko/fff.nvim/releases/download/v0.5.2/fff-mcp-aarch64-apple-darwin";
      sha256 = "sha256-RrK7HWAGrZxgNoBeG1MdY2cYqBprAQ0NwVzNKEbissk=";
    };
  };
  fff-mcp-darwin-x64 = {
    pname = "fff-mcp-darwin-x64";
    version = "0.5.2";
    src = fetchurl {
      url = "https://github.com/dmtrKovalenko/fff.nvim/releases/download/v0.5.2/fff-mcp-x86_64-apple-darwin";
      sha256 = "sha256-OY7YYI5JHQW0s84BCqOYX/lnuLF0Rt2qTtuzLbIcdZ0=";
    };
  };
  firm = {
    pname = "firm";
    version = "4144d4a08bdf285c09ed2b9781e5ec448004e506";
    src = fetchgit {
      url = "https://github.com/42futures/firm.git";
      rev = "4144d4a08bdf285c09ed2b9781e5ec448004e506";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-PgFYlw9XNxcPlRXLIBwfVV+geu3NZ9y2+puN6FczIfg=";
    };
    date = "2026-03-11";
  };
  fish-ai = {
    pname = "fish-ai";
    version = "v2.11.1";
    src = fetchFromGitHub {
      owner = "Realiserad";
      repo = "fish-ai";
      rev = "v2.11.1";
      fetchSubmodules = false;
      sha256 = "sha256-4jCOCx6bLrugIrTRz/Ut/SIMknMTXgyJJINxA9SljCA=";
    };
  };
  focaltech-fingerprint = {
    pname = "focaltech-fingerprint";
    version = "d4fbbf901aff44b92d4fa212d9b99e43cda00563";
    src = fetchgit {
      url = "https://github.com/vobademi/FTEXX00-Ubuntu.git";
      rev = "d4fbbf901aff44b92d4fa212d9b99e43cda00563";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-0mnXEQjSWUrz8uSwaeWH6uLLZtGnSUx5OPBxjPNxFTs=";
    };
    date = "2025-10-21";
  };
  fusion = {
    pname = "fusion";
    version = "ecc44eeff94dd4836eed6490a497989194effa2b";
    src = fetchgit {
      url = "https://github.com/p3psi-boo/fusion.git";
      rev = "ecc44eeff94dd4836eed6490a497989194effa2b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-O9NMromcyvcF97Kb084vrHPjqRgyRqq14Ay8pdsj9rQ=";
    };
    date = "2026-04-12";
  };
  gemma-cpp = {
    pname = "gemma-cpp";
    version = "e93b7c56f0d6f3714250482b6a91a027350d0f78";
    src = fetchgit {
      url = "https://github.com/test1111111111111112/llama-cpp-turboquant-gemma4.git";
      rev = "e93b7c56f0d6f3714250482b6a91a027350d0f78";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ykzroJr8zXnLe6Wq279/+ltTxbeSEvcbTufz2EyqYqQ=";
    };
    date = "2026-04-04";
  };
  grok2api = {
    pname = "grok2api";
    version = "5a81a63c2d92a9f5495c1098b15eb2fe133f9842";
    src = fetchgit {
      url = "https://github.com/JinchengGao-Infty/grok2api.git";
      rev = "5a81a63c2d92a9f5495c1098b15eb2fe133f9842";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-FquCukmOoCpTC+wPa+MdfMvZARLJwB1YOem61DDuVcg=";
    };
    date = "2026-03-28";
  };
  ida-mcp = {
    pname = "ida-mcp";
    version = "9.3.14";
    src = fetchurl {
      url = "https://github.com/blacktop/ida-mcp-rs/releases/download/v9.3.14/ida-mcp_9.3.14_Linux_x86_64.tar.gz";
      sha256 = "sha256-tS4nETMr+m3/RWMnynzdvIUuu5eEoW5AuTfOoJ1Xhco=";
    };
  };
  ida-pro-mcp = {
    pname = "ida-pro-mcp";
    version = "ef91fb467c3bfe266a68c3f898b93c8576eaf2c7";
    src = fetchgit {
      url = "https://github.com/QiuChenly/ida-pro-mcp-enhancement.git";
      rev = "ef91fb467c3bfe266a68c3f898b93c8576eaf2c7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Q0mqcrB/mMcSSGjVxl0528jQgdI82Ko4gCFOZITaTec=";
    };
    date = "2026-03-09";
  };
  il2cppdumper = {
    pname = "il2cppdumper";
    version = "v6.7.46";
    src = fetchFromGitHub {
      owner = "Perfare";
      repo = "Il2CppDumper";
      rev = "v6.7.46";
      fetchSubmodules = false;
      sha256 = "sha256-pMxxwBpuZ2EuP7O99XTJcnS3Dq8MdxvUGQHJ0U3bnTY=";
    };
  };
  inet-speed-cli = {
    pname = "inet-speed-cli";
    version = "v1.1.2";
    src = fetchFromGitHub {
      owner = "tsosunchia";
      repo = "iNetSpeed-CLI";
      rev = "v1.1.2";
      fetchSubmodules = false;
      sha256 = "sha256-xAXYhvN7rdXvA2EWsNXRfXlIrumyPluAcmVbMY/pZxE=";
    };
  };
  jd-gui = {
    pname = "jd-gui";
    version = "v1.6.6";
    src = fetchFromGitHub {
      owner = "java-decompiler";
      repo = "jd-gui";
      rev = "v1.6.6";
      fetchSubmodules = false;
      sha256 = "sha256-QHiZPYFwDQzbXVSuhwzQqBRXlkG9QVU+Jl6SKvBoCwQ=";
    };
  };
  komari = {
    pname = "komari";
    version = "651d24128c95206b101d1d857524b0b06ca16a7b";
    src = fetchgit {
      url = "https://github.com/komari-monitor/komari.git";
      rev = "651d24128c95206b101d1d857524b0b06ca16a7b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-3PkCpmj3AWS+zUkdIOJt9jZxS5g8CUq3Dx/wXOQjDh4=";
    };
    date = "2026-04-14";
  };
  komari-web = {
    pname = "komari-web";
    version = "d83b76fc61928ff29e1eef72aa2fc9302c16889d";
    src = fetchgit {
      url = "https://github.com/komari-monitor/komari-web.git";
      rev = "d83b76fc61928ff29e1eef72aa2fc9302c16889d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-0i/mr4bd/DAqjiYjOJLRp0HaG5ht5V2v3IUDnHvH1ec=";
    };
    date = "2026-04-10";
  };
  lazyssh = {
    pname = "lazyssh";
    version = "48995806bf1aa1c9c41bb8dff6b5ddd698539311";
    src = fetchgit {
      url = "https://github.com/p3psi-boo/lazyssh.git";
      rev = "48995806bf1aa1c9c41bb8dff6b5ddd698539311";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-/jywzjLZ51nSbiDbhw3H1eES3p0sZ9MSayGjJFQ+RKM=";
    };
    date = "2025-11-28";
  };
  lotspeed = {
    pname = "lotspeed";
    version = "3df7cb1e3526526496191edb00e2e4e92e7da761";
    src = fetchgit {
      url = "https://github.com/uk0/lotspeed.git";
      rev = "3df7cb1e3526526496191edb00e2e4e92e7da761";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Z6m93vi8u3BeQ1SW2sgKVrhHykyp/WTrcJMOaRzFJ38=";
    };
    date = "2026-01-19";
  };
  magiskboot-bin = {
    pname = "magiskboot-bin";
    version = "v30.7";
    src = fetchurl {
      url = "https://github.com/topjohnwu/Magisk/releases/download/v30.7/Magisk-v30.7.apk";
      sha256 = "sha256-4NMtISNTKGD5cSPZJ7G7hsTgjm/YpIv8a1vuCvrp69U=";
    };
  };
  mcp-cli = {
    pname = "mcp-cli";
    version = "v0.3.0";
    src = fetchFromGitHub {
      owner = "philschmid";
      repo = "mcp-cli";
      rev = "v0.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-S924rqlVKzUFD63NDyK5bbXnonra+/UoH6j78AAj3d0=";
    };
  };
  micyou = {
    pname = "micyou";
    version = "v1.2.1";
    src = fetchFromGitHub {
      owner = "LanRhyme";
      repo = "MicYou";
      rev = "v1.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-2+c1gcDqJypnuMZOxpgsT9LYK4qOmP6FtsmGY/cc2Yg=";
    };
  };
  nf_deaf = {
    pname = "nf_deaf";
    version = "cf346a3c270e5eb6d31b1d0c110efaf7a8b9193e";
    src = fetchgit {
      url = "https://github.com/kmb21y66/nf_deaf.git";
      rev = "cf346a3c270e5eb6d31b1d0c110efaf7a8b9193e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-vLcJWJtD7W1D37yFE5fGnZP6ZOKdfKkd+fTte0GDu0g=";
    };
    date = "2026-01-23";
  };
  octopus-api = {
    pname = "octopus-api";
    version = "c6485ee0bfcd4cdee867ed7d2b37c0b9938203a5";
    src = fetchgit {
      url = "https://github.com/p3psi-boo/octopus.git";
      rev = "c6485ee0bfcd4cdee867ed7d2b37c0b9938203a5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-NTQfukjK5A9s2O378heqLe0uh8++lBn6J0Od+ws1ndQ=";
    };
    date = "2026-04-18";
  };
  okmain = {
    pname = "okmain";
    version = "e51da5fa7efde11dad009592bdf3b41980c3555f";
    src = fetchgit {
      url = "https://github.com/si14/okmain.git";
      rev = "e51da5fa7efde11dad009592bdf3b41980c3555f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-klCN4sgRvN/9QyXgu0+XBJMpjTOBscNG0ZqM4CV2QBo=";
    };
    date = "2026-03-10";
  };
  oli = {
    pname = "oli";
    version = "b9e64dd0222d357de4cbd97baf02194ec4656e57";
    src = fetchgit {
      url = "https://github.com/apache/opendal-oli.git";
      rev = "b9e64dd0222d357de4cbd97baf02194ec4656e57";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Fw2Gsr8mp3OyykJJNFBchcCU7Nemzmd6asM/FAKelJc=";
    };
    date = "2026-04-02";
  };
  openalice = {
    pname = "openalice";
    version = "v0.9.0-beta.12";
    src = fetchFromGitHub {
      owner = "TraderAlice";
      repo = "OpenAlice";
      rev = "v0.9.0-beta.12";
      fetchSubmodules = false;
      sha256 = "sha256-8dSrTIBX8LpdZoDoQmxOybdjW0B6f8uriTrZay8JT3Y=";
    };
  };
  openixcli = {
    pname = "openixcli";
    version = "6f0da7324a5aa8c89e40f88b4dea2fcf5647ca11";
    src = fetchgit {
      url = "https://github.com/YuzukiTsuru/OpenixCLI.git";
      rev = "6f0da7324a5aa8c89e40f88b4dea2fcf5647ca11";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-UMa3C6rqaWRqMrzh/JCgWBfzy+xbuXD3qQIpq5vqKZs=";
    };
    date = "2026-03-21";
  };
  oura-cli = {
    pname = "oura-cli";
    version = "5354384a57006ab68ef448f196b48bf1caebb2ea";
    src = fetchgit {
      url = "https://github.com/p3psi-boo/oura-cli.git";
      rev = "5354384a57006ab68ef448f196b48bf1caebb2ea";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-hCkd7yBHND/UxRjPNU7SaG0l8MvnLgFpSgAms1quAeM=";
    };
    date = "2026-01-31";
  };
  paperclip = {
    pname = "paperclip";
    version = "b9a80dcf226c50c8778a70443e41557980376a03";
    src = fetchgit {
      url = "https://github.com/paperclipai/paperclip.git";
      rev = "b9a80dcf226c50c8778a70443e41557980376a03";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-LYslalfZ7AKSEVzjIdEWVqLn9Y6HYscskK2Y2Ps9Zo8=";
    };
    date = "2026-04-17";
  };
  pg_duckdb = {
    pname = "pg_duckdb";
    version = "318ee16cd8c647daa89198a675039726626f44b9";
    src = fetchgit {
      url = "https://github.com/duckdb/pg_duckdb.git";
      rev = "318ee16cd8c647daa89198a675039726626f44b9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-8S2uS6PgjxVzQA1gYVrEeZjnACXt3ADneDe1MlRNb/g=";
    };
    date = "2026-03-16";
  };
  planify = {
    pname = "planify";
    version = "v4.18.3";
    src = fetchFromGitHub {
      owner = "alainm23";
      repo = "planify";
      rev = "v4.18.3";
      fetchSubmodules = false;
      sha256 = "sha256-VCLXQnB3JhhK3UvnGTfR+mZ/AYGQ2YNxa6hD4QCUfjM=";
    };
  };
  polymarket-cli = {
    pname = "polymarket-cli";
    version = "v0.1.5";
    src = fetchurl {
      url = "https://github.com/Polymarket/polymarket-cli/releases/download/v0.1.5/polymarket-v0.1.5-x86_64-unknown-linux-gnu.tar.gz";
      sha256 = "sha256-3ZyMnzlliEJ+/X9ThHSyoRQ0wh/fbKkKp1oO2yvT2KY=";
    };
  };
  polymarket-cli-aarch64-linux = {
    pname = "polymarket-cli-aarch64-linux";
    version = "v0.1.5";
    src = fetchurl {
      url = "https://github.com/Polymarket/polymarket-cli/releases/download/v0.1.5/polymarket-v0.1.5-aarch64-unknown-linux-gnu.tar.gz";
      sha256 = "sha256-GjPJLG/7IRciVEltQA5Ki/aZbNAO6Q4FGZvkdgAFfNo=";
    };
  };
  proxy-ns = {
    pname = "proxy-ns";
    version = "5d08d18f9171d7e65fabad06ee81021d9bca0a21";
    src = fetchgit {
      url = "https://github.com/OkamiW/proxy-ns.git";
      rev = "5d08d18f9171d7e65fabad06ee81021d9bca0a21";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-4w5aiVpbmlGkCyg5YQnjXYkdgrbZADiWw+l4kd6ecek=";
    };
    date = "2026-04-09";
  };
  pymicro-features = {
    pname = "pymicro-features";
    version = "v2.0.2";
    src = fetchFromGitHub {
      owner = "rhasspy";
      repo = "pymicro-features";
      rev = "v2.0.2";
      fetchSubmodules = false;
      sha256 = "sha256-bCvrsvifUxM7jfqBePmcYviZ5pIy1ZApq48Pu/5b7AM=";
    };
  };
  pymicro-wakeword = {
    pname = "pymicro-wakeword";
    version = "v2.2.1";
    src = fetchFromGitHub {
      owner = "OHF-Voice";
      repo = "pymicro-wakeword";
      rev = "v2.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-PLGwpmmiLwpDn+Dh5HhaE2w7hJLC0xK/wsuhxxR8rwU=";
    };
  };
  python-mpv = {
    pname = "python-mpv";
    version = "93c4de9bb7a0e1cfcb9d305a58a326bb24ef9d47";
    src = fetchgit {
      url = "https://github.com/jaseg/python-mpv.git";
      rev = "93c4de9bb7a0e1cfcb9d305a58a326bb24ef9d47";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-fTvEcYJR7gOjmgsQkHIB+VM2rgWZLA6D/Wqa/QTyn9Q=";
    };
    date = "2025-04-25";
  };
  qmdr = {
    pname = "qmdr";
    version = "v1.0.3";
    src = fetchFromGitHub {
      owner = "uf-hy";
      repo = "qmdr";
      rev = "v1.0.3";
      fetchSubmodules = false;
      sha256 = "sha256-hVHdio3IlOU7kJwBXFuKNVTBKf+IpnamTokRPdyQ1Q0=";
    };
  };
  realitlscanner = {
    pname = "realitlscanner";
    version = "v0.2.1";
    src = fetchFromGitHub {
      owner = "XTLS";
      repo = "RealiTLScanner";
      rev = "v0.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-rshU3nBguzBleM9zlPHPFQy0C+C6LYE2EI1uKRl4DN4=";
    };
  };
  rikugan = {
    pname = "rikugan";
    version = "v1.2.1";
    src = fetchFromGitHub {
      owner = "buzzer-re";
      repo = "Rikugan";
      rev = "v1.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-JUiC6CZ0xqOj1t1w80RSHhXLiSXda8nX+HIJEUZvsTM=";
    };
  };
  rime-custom-pinyin-dictionary = {
    pname = "rime-custom-pinyin-dictionary";
    version = "20260101";
    src = fetchurl {
      url = "https://github.com/wuhgit/CustomPinyinDictionary/releases/download/assets/CustomPinyinDictionary_Fcitx.dict";
      sha256 = "sha256-Y2d7DhvNknbo7u9BVTq1Mr9gYSeFWNnvo2KbDr6INuU=";
    };
  };
  sigmo = {
    pname = "sigmo";
    version = "v4.0.3";
    src = fetchFromGitHub {
      owner = "damonto";
      repo = "sigmo";
      rev = "v4.0.3";
      fetchSubmodules = false;
      sha256 = "sha256-5syKKb+dSdFL52j/gCwoM4ClRZe0PL9ch3AMqhhmQ0k=";
    };
  };
  smali = {
    pname = "smali";
    version = "v2.5.2";
    src = fetchFromGitHub {
      owner = "JesusFreke";
      repo = "smali";
      rev = "v2.5.2";
      fetchSubmodules = false;
      sha256 = "sha256-UkABsX7KaDZyFR4MTmpjnw4dGXChbLB281Kav/k7/00=";
    };
  };
  sofixer = {
    pname = "sofixer";
    version = "v2.1.7";
    src = fetchFromGitHub {
      owner = "F8LEFT";
      repo = "SoFixer";
      rev = "v2.1.7";
      fetchSubmodules = false;
      sha256 = "sha256-emvN0iNPoADAiH4eOPCIViNHpItKyacySu/9EK2BaeQ=";
    };
  };
  srv-us = {
    pname = "srv-us";
    version = "664ef6a4fab24c5f3f1fc2fa07cc3e0c43d90cf9";
    src = fetchgit {
      url = "https://github.com/p3psi-boo/srv.us.git";
      rev = "664ef6a4fab24c5f3f1fc2fa07cc3e0c43d90cf9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-CEaSHwR8munYwKkLkCAGGbnRsel+by72QBY28lIRQO4=";
    };
    date = "2026-02-08";
  };
  substack-dl = {
    pname = "substack-dl";
    version = "866b2566f9244374e7df5f0f404098c5f81e7b06";
    src = fetchFromGitHub {
      owner = "p3psi-boo";
      repo = "substack-dl";
      rev = "866b2566f9244374e7df5f0f404098c5f81e7b06";
      fetchSubmodules = false;
      sha256 = "sha256-F8497VhGZXCyYd2pHaJKr1WXWKEbUSSQ+3LaA1cnZXs=";
    };
    date = "2022-08-08";
  };
  tcp-brutal = {
    pname = "tcp-brutal";
    version = "204aeea3437a83599c1c1fa1b97e4425cfdfc49d";
    src = fetchgit {
      url = "https://github.com/apernet/tcp-brutal.git";
      rev = "204aeea3437a83599c1c1fa1b97e4425cfdfc49d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-rx8JgQtelssslJhFAEKq73LsiHGPoML9Gxvw0lsLacI=";
    };
    date = "2024-07-27";
  };
  uber-apk-signer = {
    pname = "uber-apk-signer";
    version = "v1.3.0";
    src = fetchFromGitHub {
      owner = "patrickfav";
      repo = "uber-apk-signer";
      rev = "v1.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-pxGzRAUuYUyqcanoaQ4rqbZQfLMWdmc4GdGBeLw7O+M=";
    };
  };
  ut = {
    pname = "ut";
    version = "6ea80d7d40c67d81569ddc814b9ef9e835dff388";
    src = fetchgit {
      url = "https://github.com/ksdme/ut.git";
      rev = "6ea80d7d40c67d81569ddc814b9ef9e835dff388";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-SURksZzJS3ouJIyfV7K4PkToPBs7hmOD2xT7IeebWco=";
    };
    date = "2025-12-26";
  };
  vanissh = {
    pname = "vanissh";
    version = "c2ee4700d8112b5c6f06fd587b6f11c9aafbdf72";
    src = fetchgit {
      url = "https://github.com/k4yt3x/vanissh.git";
      rev = "c2ee4700d8112b5c6f06fd587b6f11c9aafbdf72";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-5pn2gKiGnd5nfGv3qjaFdvWzMnFjWLUwLtoZb8es7YE=";
    };
    date = "2025-09-21";
  };
  vgpu_unlock-rs = {
    pname = "vgpu_unlock-rs";
    version = "v19.1";
    src = fetchFromGitHub {
      owner = "rbqvq";
      repo = "vgpu_unlock-rs";
      rev = "v19.1";
      fetchSubmodules = false;
      sha256 = "sha256-CdLh8OU/idWLzdPEfQpF5Uost1vaNSEJkBJJlHdPb1c=";
    };
  };
  vikunja-cli = {
    pname = "vikunja-cli";
    version = "7d96f181c2e0e07b4e75c7f540e9a8cfdf9065dc";
    src = fetchgit {
      url = "https://github.com/p3psi-boo/vikunja-cli.git";
      rev = "7d96f181c2e0e07b4e75c7f540e9a8cfdf9065dc";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ZxsFScCas6Uvt91eWzdwfTAsWZnVooRp/QaIp2IdHVw=";
    };
    date = "2026-02-25";
  };
  vllm = {
    pname = "vllm";
    version = "v0.19.0";
    src = fetchFromGitHub {
      owner = "vllm-project";
      repo = "vllm";
      rev = "v0.19.0";
      fetchSubmodules = false;
      sha256 = "sha256-0gM52DDfLzkE4QXCGR3c3Jq4CQ1PrnDj4Ky0lsUJ2a8=";
    };
  };
  web-search = {
    pname = "web-search";
    version = "d3be36dc80cc5d8f91df78ddb0d1a018d49d5e70";
    src = fetchgit {
      url = "https://github.com/p3psi-boo/web-search.git";
      rev = "d3be36dc80cc5d8f91df78ddb0d1a018d49d5e70";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-7eTnPf+pb2yFK/qrLP37GI96EqexbWDHqfNhoMYNdJg=";
    };
    date = "2026-03-21";
  };
  wikiteam3 = {
    pname = "wikiteam3";
    version = "06346a4305f8f8c5ced633c3e0dc38b3bb960e6e";
    src = fetchgit {
      url = "https://github.com/saveweb/wikiteam3.git";
      rev = "06346a4305f8f8c5ced633c3e0dc38b3bb960e6e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-gdUZzfIn9nM60+mYacFblmyqa+pY+EbR4lPZnuy6Amk=";
    };
    date = "2025-12-24";
  };
  wsl-vpnkit = {
    pname = "wsl-vpnkit";
    version = "v0.4.1";
    src = fetchFromGitHub {
      owner = "sakai135";
      repo = "wsl-vpnkit";
      rev = "v0.4.1";
      fetchSubmodules = false;
      sha256 = "sha256-Igbr3L2W32s4uBepllSz07bkbI3qwAKMZkBrXLqGrGA=";
    };
  };
}
